"""add created_at to issues

Revision ID: 095abd006b19
Revises: aa2d3df460bd
Create Date: 2025-09-16 12:35:00.961628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '095abd006b19'
down_revision: Union[str, Sequence[str], None] = 'aa2d3df460bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'created_at')
    # ### end Alembic commands ###
