"""add floor_plan and extracted_details to floors

Revision ID: 114f47ddfec9
Revises: e3c21b5eef63
Create Date: 2025-08-28 15:02:23.961564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '114f47ddfec9'
down_revision: Union[str, Sequence[str], None] = 'e3c21b5eef63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('floors', sa.Column('floor_plan', sa.String(), nullable=True))
    op.add_column('floors', sa.Column('extracted_details', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('floors', 'extracted_details')
    op.drop_column('floors', 'floor_plan')
    # ### end Alembic commands ###
