"""Add category to vendors

Revision ID: 1270fa92a949
Revises: 095abd006b19
Create Date: 2025-09-17 11:40:04.306290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1270fa92a949'
down_revision: Union[str, Sequence[str], None] = '095abd006b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issues', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('issues', 'property_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('issues', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('vendors', sa.Column('category', sa.String(), nullable=False))
    op.alter_column('vendors', 'contact',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('vendors', 'total_jobs')
    op.drop_column('vendors', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('total_jobs', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('vendors', 'contact',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('vendors', 'category')
    op.alter_column('issues', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('issues', 'property_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('issues', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
