"""Add user_id to ActivityLog

Revision ID: 456b6e9acbf8
Revises: d91ad7205559
Create Date: 2025-08-14 15:04:57.111396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '456b6e9acbf8'
down_revision: Union[str, Sequence[str], None] = 'd91ad7205559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'activity_logs', 'users', ['user_id'], ['id'])
    op.drop_column('activity_logs', 'timestamp')
    op.drop_column('activity_logs', 'user')
    op.drop_column('activity_logs', 'action')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('action', sa.VARCHAR(), nullable=False))
    op.add_column('activity_logs', sa.Column('user', sa.VARCHAR(), nullable=False))
    op.add_column('activity_logs', sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.drop_column('activity_logs', 'user_id')
    # ### end Alembic commands ###
