"""fix models relationships

Revision ID: 4b0da0e430a4
Revises: b5b60764f317
Create Date: 2025-08-20 11:22:04.740116
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4b0da0e430a4'
down_revision: Union[str, Sequence[str], None] = 'b5b60764f317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 🚨 Removed op.alter_column because SQLite doesn’t support it
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 🚨 Removed op.alter_column for SQLite
    pass
    # ### end Alembic commands ###
