"""Add assigned_to to Issue

Revision ID: 543a535007b5
Revises: e89421ff8015
Create Date: 2025-09-18 14:38:27.005214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '543a535007b5'
down_revision: Union[str, Sequence[str], None] = 'e89421ff8015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.add_column('issues', sa.Column('assigned_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'issues', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_column('issues', 'assigned_at')
    op.drop_column('issues', 'assigned_to')
    # ### end Alembic commands ###
