"""Add image fields to appliances

Revision ID: 5c099865c2f6
Revises: 4b0da0e430a4
Create Date: 2025-08-22 10:16:20.595549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c099865c2f6'
down_revision: Union[str, Sequence[str], None] = '4b0da0e430a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appliance_images_id'), table_name='appliance_images')
    op.drop_table('appliance_images')
    op.add_column('appliances', sa.Column('detail_image', sa.String(), nullable=True))
    op.alter_column('appliances', 'image',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'default_appliance.png'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appliances', 'image',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'default_appliance.png'"))
    op.drop_column('appliances', 'detail_image')
    op.create_table('appliance_images',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('appliance_id', sa.INTEGER(), nullable=False),
    sa.Column('image_path', sa.VARCHAR(), nullable=False),
    sa.Column('side', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['appliance_id'], ['appliances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appliance_images_id'), 'appliance_images', ['id'], unique=False)
    # ### end Alembic commands ###
