"""Add assigned_to column to issues

Revision ID: 654dbc843905
Revises: 1270fa92a949
Create Date: 2025-09-17 12:25:37.393633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '654dbc843905'
down_revision: Union[str, Sequence[str], None] = '1270fa92a949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.alter_column('issues', 'status',
               existing_type=postgresql.ENUM('pending', 'assigned', 'completed', 'verified', name='issuestatus'),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'issues', 'vendors', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.alter_column('issues', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('pending', 'assigned', 'completed', 'verified', name='issuestatus'),
               existing_nullable=True)
    op.drop_column('issues', 'assigned_to')
    # ### end Alembic commands ###
