"""add appliance_id to issues

Revision ID: bec6e2119756
Revises: db513336e6e5
Create Date: 2025-09-16 10:18:11.875409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bec6e2119756'
down_revision: Union[str, Sequence[str], None] = 'db513336e6e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('appliance_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'issues', 'appliances', ['appliance_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_column('issues', 'appliance_id')
    # ### end Alembic commands ###
