"""Add service_type to users

Revision ID: e89421ff8015
Revises: 654dbc843905
Create Date: 2025-09-18 13:35:15.807854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e89421ff8015'
down_revision: Union[str, Sequence[str], None] = '654dbc843905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issues', 'bill_amount',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_foreign_key(None, 'issues', 'users', ['vendor_id'], ['id'])
    op.drop_column('issues', 'assigned_to')
    op.drop_column('issues', 'bill_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('bill_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('issues', sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.alter_column('issues', 'bill_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    # ### end Alembic commands ###
