"""fix tenant_queries model

Revision ID: f500d8b20d14
Revises: 1776baee6abb
Create Date: 2025-09-15 15:05:22.629087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f500d8b20d14'
down_revision: Union[str, Sequence[str], None] = '1776baee6abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_queries', sa.Column('description', sa.String(), nullable=False))
    op.add_column('tenant_queries', sa.Column('status', sa.String(), nullable=True))
    op.add_column('tenant_queries', sa.Column('reported_by_id', sa.Integer(), nullable=True))
    op.add_column('tenant_queries', sa.Column('appliance_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('tenant_queries_user_id_fkey'), 'tenant_queries', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_queries', 'users', ['reported_by_id'], ['id'])
    op.create_foreign_key(None, 'tenant_queries', 'appliances', ['appliance_id'], ['id'])
    op.drop_column('tenant_queries', 'message')
    op.drop_column('tenant_queries', 'subject')
    op.drop_column('tenant_queries', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_queries', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tenant_queries', sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('tenant_queries', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tenant_queries', type_='foreignkey')
    op.drop_constraint(None, 'tenant_queries', type_='foreignkey')
    op.create_foreign_key(op.f('tenant_queries_user_id_fkey'), 'tenant_queries', 'users', ['user_id'], ['id'])
    op.drop_column('tenant_queries', 'appliance_id')
    op.drop_column('tenant_queries', 'reported_by_id')
    op.drop_column('tenant_queries', 'status')
    op.drop_column('tenant_queries', 'description')
    # ### end Alembic commands ###
